<a href="https://colab.research.google.com/github/kimjaehwankimjaehwan/deeplearningstudy/blob/main/pandas_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
img_list = []

In [ ]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.random.random((2,3))

array([[0.9607098 , 0.10448811, 0.41117406],
       [0.1123647 , 0.63768465, 0.13505567]])

In [ ]:
arr = np.array([[1,20,3],[4,5,6]])
arr

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
arr.sum()

np.int64(39)

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(20)

In [ ]:
arr.mean()

np.float64(6.5)

In [ ]:
np.sort(arr)

array([[ 1,  3, 20],
       [ 4,  5,  6]])

In [ ]:
arr

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
-np.sort(-arr)

array([[20,  3,  1],
       [ 6,  5,  4]])

In [ ]:
np.sort(-arr)

array([[-20,  -3,  -1],
       [ -6,  -5,  -4]])

In [ ]:
-np.sort(-arr)

array([[20,  3,  1],
       [ 6,  5,  4]])

In [ ]:
arr.T

array([[ 1,  4],
       [20,  5],
       [ 3,  6]])

In [ ]:
arr.ravel()

array([ 1, 20,  3,  4,  5,  6])

In [ ]:
np.sort(arr.ravel())

array([ 1,  3,  4,  5,  6, 20])

In [ ]:
-np.sort(-arr.ravel())

array([20,  6,  5,  4,  3,  1])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.reshape(1,6)

array([[ 1, 20,  3,  4,  5,  6]])

In [ ]:
arr.reshape(1,-1)

array([[ 1, 20,  3,  4,  5,  6]])

In [ ]:
arr.reshape(6,1)

array([[ 1],
       [20],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])

In [ ]:
arr.reshape(2,-1)

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
arr.reshape(6,1)

array([[ 1],
       [20],
       [ 3],
       [ 4],
       [ 5],
       [ 6]])

In [ ]:
arr_a = np.arange(5)

In [ ]:
arr_a

array([0, 1, 2, 3, 4])

배열붙이기

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
arr1 + arr2

array([5, 7, 9])

In [ ]:
np.append(arr1, arr2)

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[7,8,9],[10,11,12]])

In [ ]:
np.append(arr3, arr4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.concatenate([arr3, arr4], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr3, arr4], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.concatenate([arr3, arr4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [ ]:
np.insert(arr, 3, 10)

array([ 1, 20,  3, 10,  4,  5,  6])

In [ ]:
np.insert(arr, 4, 10)

array([ 1, 20,  3,  4, 10,  5,  6])

In [ ]:
np.delete(arr,2)

array([ 1, 20,  4,  5,  6])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.read_csv('/content/drive/MyDrive/kdt_2506/data/trade_apt_api.csv')

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
pd.read_csv('/content/drive/MyDrive/kdt_2506/data/trade_apt_api.csv',encoding='utf-8')

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
data = [1,2,3,4,5]
df = pd.DataFrame(data) # np.array()

In [ ]:
df

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
df.to_csv('test.csv')

In [ ]:
pd.read_csv('/content/test.csv')

Unnamed: 0  0
0           0  1
1           1  2
2           2  3
3           3  4
4           4  5

In [ ]:
df.to_csv('/content/test2.csv',index=False)

In [ ]:
pd.read_csv('/content/test2.csv')

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
df.to_csv('/content/drive/MyDrive/kdt_2506/data/test2.csv',encoding='utf-8')

In [ ]:
df_load = pd.read_csv('/content/drive/MyDrive/kdt_2506/data/test2.csv',encoding='utf-8')
df_load

Unnamed: 0  0
0           0  1
1           1  2
2           2  3
3           3  4
4           4  5

In [ ]:
df.to_csv('/content/drive/MyDrive/kdt_2506/data/test3.csv',encoding='utf-8', index=False)

In [ ]:
df_load2 = pd.read_csv('/content/drive/MyDrive/kdt_2506/data/test3.csv',encoding='utf-8')
df_load2

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/kdt_2506/data/trade_apt_api.csv',encoding='utf-8')
df

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df.head()

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0  202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   

   건축년도    전용면적  층  
0  2002  134.66  5  
1  2008  126.34  7  
2  2008   94.28  5  
3  2008   97.61  1  
4  2008   94.51  5

In [ ]:
df.head(10)

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0  202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
5  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
6  202006  서울특별시종로구  11110  사직동       광화문풍림스페이스본(106동)  146000  2020  6  22   
7  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  130000  2020  6  24   
8  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  112000  2020  6  24   
9  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  145000  2020  6  26   

   건축년도    전용면적   층  
0  2002  134.66   5  
1  2008  126.34   7  
2  2008   94.28   5  
3  2008   97.61   1  
4  2008   94.51   5  
5  2008   91.35  14  
6  2008  150.40   7  
7  2008   94.51  14  
8  2008   94.28   1  
9  2008  126.34   6

In [ ]:
df.tail()

기준년월       지역명   지역코드  법정동      아파트    거래금액     년  월   일  건축년도  \
113  202006  서울특별시종로구  11110  무악동       현대  100990  2020  6  23  2000   
114  202006  서울특별시종로구  11110  무악동  인왕산아이파크   97000  2020  6  23  2008   
115  202006  서울특별시종로구  11110  무악동  인왕산아이파크  120000  2020  6  27  2008   
116  202006  서울특별시종로구  11110  무악동       현대   74990  2020  6  27  2000   
117  202006  서울특별시종로구  11110  무악동       현대  110900  2020  6  30  2000   

        전용면적   층  
113   84.920  13  
114   84.858   2  
115   84.858   9  
116   60.000   6  
117  114.900   4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   기준년월    118 non-null    int64  
 1   지역명     118 non-null    object 
 2   지역코드    118 non-null    int64  
 3   법정동     118 non-null    object 
 4   아파트     118 non-null    object 
 5   거래금액    118 non-null    int64  
 6   년       118 non-null    int64  
 7   월       118 non-null    int64  
 8   일       118 non-null    int64  
 9   건축년도    118 non-null    int64  
 10  전용면적    118 non-null    float64
 11  층       118 non-null    int64  
dtypes: float64(1), int64(8), object(3)
memory usage: 11.2+ KB


In [ ]:
df.describe()

기준년월     지역코드           거래금액       년      월           일  \
count     118.0    118.0     118.000000   118.0  118.0  118.000000   
mean   202006.0  11110.0   90147.881356  2020.0    6.0   16.923729   
std         0.0      0.0   42873.163639     0.0    0.0    8.036409   
min    202006.0  11110.0   11200.000000  2020.0    6.0    1.000000   
25%    202006.0  11110.0   57200.000000  2020.0    6.0   12.000000   
50%    202006.0  11110.0   79500.000000  2020.0    6.0   17.000000   
75%    202006.0  11110.0  120000.000000  2020.0    6.0   23.000000   
max    202006.0  11110.0  178500.000000  2020.0    6.0   30.000000   

              건축년도        전용면적           층  
count   118.000000  118.000000  118.000000  
mean   2001.771186   87.524769    7.635593  
std      10.838686   36.626369    4.649539  
min    1966.000000   12.780000    1.000000  
25%    1993.000000   59.983250    4.000000  
50%    2003.500000   84.847000    7.000000  
75%    2008.000000  106.620000   10.000000  
max    2019.000000  218.860000   19.000000

In [ ]:
df.columns

Index(['기준년월', '지역명', '지역코드', '법정동', '아파트', '거래금액', '년', '월', '일', '건축년도',
       '전용면적', '층'],
      dtype='object')

In [ ]:
df.values

array([[202006, '서울특별시종로구', 11110, ..., 2002, 134.66, 5],
       [202006, '서울특별시종로구', 11110, ..., 2008, 126.34, 7],
       [202006, '서울특별시종로구', 11110, ..., 2008, 94.28, 5],
       ...,
       [202006, '서울특별시종로구', 11110, ..., 2008, 84.858, 9],
       [202006, '서울특별시종로구', 11110, ..., 2000, 60.0, 6],
       [202006, '서울특별시종로구', 11110, ..., 2000, 114.9, 4]], dtype=object)

In [ ]:
df.index

RangeIndex(start=0, stop=118, step=1)

In [ ]:
df.shape

(118, 12)

In [ ]:
df['기준년월'].dtype

dtype('int64')

In [ ]:
df['지역명'].dtype

dtype('O')

In [ ]:
df['전용면적'].dtype

dtype('float64')

In [ ]:
df.nunique()

기준년월      1
지역명       1
지역코드      1
법정동      15
아파트      38
거래금액    102
년         1
월         1
일        27
건축년도     24
전용면적     61
층        19
dtype: int64

In [ ]:
df['지역명'].unique()

array(['서울특별시종로구'], dtype=object)

In [ ]:
df['법정동'].unique()

array(['신교동', '사직동', '당주동', '내수동', '익선동', '인의동', '명륜2가', '창신동', '숭인동',
       '평동', '홍파동', '교북동', '구기동', '평창동', '무악동'], dtype=object)

In [ ]:
df['법정동'].value_counts()

법정동
창신동     39
무악동     16
숭인동     12
홍파동     10
사직동      9
내수동      7
평창동      7
인의동      5
평동       5
명륜2가     2
익선동      2
신교동      1
당주동      1
구기동      1
교북동      1
Name: count, dtype: int64

In [ ]:
len(df)

118

In [ ]:
df['법정동'].value_counts()

법정동
창신동     39
무악동     16
숭인동     12
홍파동     10
사직동      9
내수동      7
평창동      7
인의동      5
평동       5
명륜2가     2
익선동      2
신교동      1
당주동      1
구기동      1
교북동      1
Name: count, dtype: int64

In [ ]:
df.sum()

기준년월                                             23836708
지역명     서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종...
지역코드                                              1310980
법정동     신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내...
아파트     신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...
거래금액                                             10637450
년                                                  238360
월                                                     708
일                                                    1997
건축년도                                               236209
전용면적                                           10327.9228
층                                                     901
dtype: object

In [ ]:
df['층'].sum()

np.int64(901)

In [ ]:
df.cumsum()

기준년월                                                지역명     지역코드  \
0      202006                                           서울특별시종로구    11110   
1      404012                                   서울특별시종로구서울특별시종로구    22220   
2      606018                           서울특별시종로구서울특별시종로구서울특별시종로구    33330   
3      808024                   서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구    44440   
4     1010030           서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구    55550   
..        ...                                                ...      ...   
113  23028684  서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종...  1266540   
114  23230690  서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종...  1277650   
115  23432696  서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종...  1288760   
116  23634702  서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종...  1299870   
117  23836708  서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종...  1310980   

                                                   법정동  \
0                                                  신교동   
1                                               신교동사직동   
2                                            신교동사직동사직동   
3                                         신교동사직동사직동사직동   
4                                      신교동사직동사직동사직동사직동   
..                                                 ...   
113  신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내...   
114  신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내...   
115  신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내...   
116  신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내...   
117  신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내...   

                                                   아파트      거래금액       년    월  \
0                                             신현(102동)    100000    2020    6   
1                        신현(102동)광화문풍림스페이스본(101동~105동)    221500    4040   12   
2    신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...    336500    6060   18   
3    신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...    449500    8080   24   
4    신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...    573500   10100   30   
..                                                 ...       ...     ...  ...   
113  신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...  10234560  230280  684   
114  신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...  10331560  232300  690   
115  신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...  10451560  234320  696   
116  신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...  10526550  236340  702   
117  신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~1...  10637450  238360  708   

        일    건축년도        전용면적    층  
0      30    2002    134.6600    5  
1      34    4010    261.0000   12  
2      43    6018    355.2800   17  
3      56    8026    452.8900   18  
4      72   10034    547.4000   23  
..    ...     ...         ...  ...  
113  1890  228193   9983.3068  880  
114  1913  230201  10068.1648  882  
115  1940  232209  10153.0228  891  
116  1967  234209  10213.0228  897  
117  1997  236209  10327.9228  901  

[118 rows x 12 columns]

In [ ]:
df['전용면적'].cumsum()

0        134.6600
1        261.0000
2        355.2800
3        452.8900
4        547.4000
          ...    
113     9983.3068
114    10068.1648
115    10153.0228
116    10213.0228
117    10327.9228
Name: 전용면적, Length: 118, dtype: float64

In [ ]:
df.mean()

TypeError: Could not convert ['서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구서울특별시종로구'
 '신교동사직동사직동사직동사직동사직동사직동사직동사직동사직동당주동내수동내수동내수동내수동내수동내수동내수동익선동익선동인의동인의동인의동인의동인의동명륜2가명륜2가창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동창신동숭인동숭인동숭인동숭인동숭인동숭인동숭인동숭인동숭인동숭인동숭인동숭인동평동평동평동평동평동홍파동홍파동홍파동홍파동홍파동홍파동홍파동홍파동홍파동홍파동교북동구기동평창동평창동평창동평창동평창동평창동평창동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동무악동'
 '신현(102동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(106동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~105동)광화문풍림스페이스본(101동~105동)세종경희궁의아침2단지경희궁의아침3단지세종로대우경희궁의아침3단지경희궁의아침3단지킹스매너경희궁의아침2단지현대뜨레비앙운현신화타워효성쥬얼리시티효성쥬얼리시티효성쥬얼리시티효성쥬얼리시티효성쥬얼리시티아남1아남1창신쌍용1창신쌍용2창신쌍용2창신쌍용1동대문맨션창신쌍용2창신쌍용1창신쌍용1MID그린(8동)창신쌍용2창신쌍용2창신쌍용2창신쌍용2창신쌍용2창신쌍용2창신쌍용2창신쌍용2창신쌍용1창신쌍용1창신쌍용1창신쌍용2유성일우창신쌍용2동대문창신쌍용1두산창신쌍용2창신쌍용1두산두산창신쌍용2동대문창신쌍용2브라운스톤창신창신쌍용1동대문창신쌍용1창신쌍용1종로센트레빌종로센트레빌종로중흥S클래스종로센트레빌종로청계힐스테이트종로센트레빌숭인상가종로센트레빌삼전솔하임4차숭인한양LEEPS버넷하임1종로센트레빌경희궁자이(3단지)경희궁자이(3단지)경희궁자이(3단지)경희궁자이(3단지)경희궁자이(3단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)경희궁자이(2단지)동아마운틴뷰롯데낙천대롯데낙천대롯데낙천대엘리시아엘리시아밀레니엄밀레니엄무악다온채현대인왕산아이파크인왕산아이파크인왕산아이파크현대현대인왕산아이파크현대현대현대현대인왕산아이파크인왕산아이파크현대현대'] to numeric

In [ ]:
df['전용면적'].mean()

np.float64(87.52476949152543)

In [ ]:
df.median()

TypeError: Cannot convert [['서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구'
  '서울특별시종로구' '서울특별시종로구' '서울특별시종로구' '서울특별시종로구']
 ['신교동' '사직동' '사직동' '사직동' '사직동' '사직동' '사직동' '사직동' '사직동' '사직동' '당주동' '내수동'
  '내수동' '내수동' '내수동' '내수동' '내수동' '내수동' '익선동' '익선동' '인의동' '인의동' '인의동' '인의동'
  '인의동' '명륜2가' '명륜2가' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동'
  '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동'
  '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동'
  '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '창신동' '숭인동' '숭인동' '숭인동' '숭인동' '숭인동'
  '숭인동' '숭인동' '숭인동' '숭인동' '숭인동' '숭인동' '숭인동' '평동' '평동' '평동' '평동' '평동'
  '홍파동' '홍파동' '홍파동' '홍파동' '홍파동' '홍파동' '홍파동' '홍파동' '홍파동' '홍파동' '교북동' '구기동'
  '평창동' '평창동' '평창동' '평창동' '평창동' '평창동' '평창동' '무악동' '무악동' '무악동' '무악동' '무악동'
  '무악동' '무악동' '무악동' '무악동' '무악동' '무악동' '무악동' '무악동' '무악동' '무악동' '무악동']
 ['신현(102동)' '광화문풍림스페이스본(101동~105동)' '광화문풍림스페이스본(101동~105동)'
  '광화문풍림스페이스본(101동~105동)' '광화문풍림스페이스본(101동~105동)' '광화문풍림스페이스본(101동~105동)'
  '광화문풍림스페이스본(106동)' '광화문풍림스페이스본(101동~105동)' '광화문풍림스페이스본(101동~105동)'
  '광화문풍림스페이스본(101동~105동)' '세종' '경희궁의아침2단지' '경희궁의아침3단지' '세종로대우'
  '경희궁의아침3단지' '경희궁의아침3단지' '킹스매너' '경희궁의아침2단지' '현대뜨레비앙' '운현신화타워' '효성쥬얼리시티'
  '효성쥬얼리시티' '효성쥬얼리시티' '효성쥬얼리시티' '효성쥬얼리시티' '아남1' '아남1' '창신쌍용1' '창신쌍용2'
  '창신쌍용2' '창신쌍용1' '동대문맨션' '창신쌍용2' '창신쌍용1' '창신쌍용1' 'MID그린(8동)' '창신쌍용2'
  '창신쌍용2' '창신쌍용2' '창신쌍용2' '창신쌍용2' '창신쌍용2' '창신쌍용2' '창신쌍용2' '창신쌍용1' '창신쌍용1'
  '창신쌍용1' '창신쌍용2' '유성' '일우' '창신쌍용2' '동대문' '창신쌍용1' '두산' '창신쌍용2' '창신쌍용1'
  '두산' '두산' '창신쌍용2' '동대문' '창신쌍용2' '브라운스톤창신' '창신쌍용1' '동대문' '창신쌍용1' '창신쌍용1'
  '종로센트레빌' '종로센트레빌' '종로중흥S클래스' '종로센트레빌' '종로청계힐스테이트' '종로센트레빌' '숭인상가'
  '종로센트레빌' '삼전솔하임4차' '숭인한양LEEPS' '버넷하임1' '종로센트레빌' '경희궁자이(3단지)'
  '경희궁자이(3단지)' '경희궁자이(3단지)' '경희궁자이(3단지)' '경희궁자이(3단지)' '경희궁자이(2단지)'
  '경희궁자이(2단지)' '경희궁자이(2단지)' '경희궁자이(2단지)' '경희궁자이(2단지)' '경희궁자이(2단지)'
  '경희궁자이(2단지)' '경희궁자이(2단지)' '경희궁자이(2단지)' '경희궁자이(2단지)' '동아' '마운틴뷰' '롯데낙천대'
  '롯데낙천대' '롯데낙천대' '엘리시아' '엘리시아' '밀레니엄' '밀레니엄' '무악다온채' '현대' '인왕산아이파크'
  '인왕산아이파크' '인왕산아이파크' '현대' '현대' '인왕산아이파크' '현대' '현대' '현대' '현대' '인왕산아이파크'
  '인왕산아이파크' '현대' '현대']] to numeric

In [ ]:
df['전용면적'].median()

84.84700000000001

In [ ]:
df.max()

기준년월      202006
지역명     서울특별시종로구
지역코드       11110
법정동          홍파동
아파트      효성쥬얼리시티
거래금액      178500
년           2020
월              6
일             30
건축년도        2019
전용면적      218.86
층             19
dtype: object

In [ ]:
df['거래금액'].max()

178500

In [ ]:
df.min()

기준년월       202006
지역명      서울특별시종로구
지역코드        11110
법정동           교북동
아파트     MID그린(8동)
거래금액        11200
년            2020
월               6
일               1
건축년도         1966
전용면적        12.78
층               1
dtype: object

In [ ]:
df['층'].min() , df['거래금액'].min()

(1, 11200)

In [ ]:
df.count()

기준년월    118
지역명     118
지역코드    118
법정동     118
아파트     118
거래금액    118
년       118
월       118
일       118
건축년도    118
전용면적    118
층       118
dtype: int64

In [ ]:
df.size

1416

In [ ]:
# df.var()
df["전용면적"].var()

1341.4909063040182

In [ ]:
# df.std()
df['전용면적'].std()

36.6263690024553

In [ ]:
df

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df.loc[:,:]

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df.loc[0:2,["아파트",'거래금액']]

아파트    거래금액
0               신현(102동)  100000
1  광화문풍림스페이스본(101동~105동)  121500
2  광화문풍림스페이스본(101동~105동)  115000

In [ ]:
df.loc[:,['아파트']].head(3)

아파트
0               신현(102동)
1  광화문풍림스페이스본(101동~105동)
2  광화문풍림스페이스본(101동~105동)

In [ ]:
df.loc[:,["아파트",'거래금액']].tail(3)

아파트    거래금액
115  인왕산아이파크  120000
116       현대   74990
117       현대  110900

In [ ]:
df.loc[:5,'지역명':'아파트']

지역명   지역코드  법정동                    아파트
0  서울특별시종로구  11110  신교동               신현(102동)
1  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)
2  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)
3  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)
4  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)
5  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)

In [ ]:
df.loc[:5,['지역명','아파트']]

지역명                    아파트
0  서울특별시종로구               신현(102동)
1  서울특별시종로구  광화문풍림스페이스본(101동~105동)
2  서울특별시종로구  광화문풍림스페이스본(101동~105동)
3  서울특별시종로구  광화문풍림스페이스본(101동~105동)
4  서울특별시종로구  광화문풍림스페이스본(101동~105동)
5  서울특별시종로구  광화문풍림스페이스본(101동~105동)

In [ ]:
df.loc[:10,'지역명':]

지역명   지역코드  법정동                    아파트    거래금액     년  월   일  건축년도  \
0   서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30  2002   
1   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4  2008   
2   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9  2008   
3   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13  2008   
4   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16  2008   
5   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20  2008   
6   서울특별시종로구  11110  사직동       광화문풍림스페이스본(106동)  146000  2020  6  22  2008   
7   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  130000  2020  6  24  2008   
8   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  112000  2020  6  24  2008   
9   서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  145000  2020  6  26  2008   
10  서울특별시종로구  11110  당주동                     세종   79000  2020  6  15  1983   

      전용면적   층  
0   134.66   5  
1   126.34   7  
2    94.28   5  
3    97.61   1  
4    94.51   5  
5    91.35  14  
6   150.40   7  
7    94.51  14  
8    94.28   1  
9   126.34   6  
10  102.89   5

In [ ]:
print(df.loc[0,'건축년도'])

2002


In [ ]:
df

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df.loc[df['층'] > 7].head(5)

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
5   202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
7   202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  130000  2020  6  24   
12  202006  서울특별시종로구  11110  내수동              경희궁의아침3단지  172000  2020  6   5   
13  202006  서울특별시종로구  11110  내수동                  세종로대우   95000  2020  6   5   
14  202006  서울특별시종로구  11110  내수동              경희궁의아침3단지  155000  2020  6   9   

    건축년도    전용면적   층  
5   2008   91.35  14  
7   2008   94.51  14  
12  2004  174.55  11  
13  1994  109.91  11  
14  2004  149.00  14

In [ ]:
df.loc[(df['아파트']=='인왕산아이파크') & (df['전용면적'] >= 100)]

기준년월       지역명   지역코드  법정동      아파트    거래금액     년  월   일  건축년도  \
106  202006  서울특별시종로구  11110  무악동  인왕산아이파크  135000  2020  6  16  2008   
109  202006  서울특별시종로구  11110  무악동  인왕산아이파크  139000  2020  6  17  2008   

        전용면적   층  
106  114.931  12  
109  114.931  13

In [ ]:
df.loc[:3,'건축년도']

0    2002
1    2008
2    2008
3    2008
Name: 건축년도, dtype: int64

In [ ]:
df['층']> 7

0      False
1      False
2      False
3      False
4      False
       ...  
113     True
114    False
115     True
116    False
117    False
Name: 층, Length: 118, dtype: bool

In [ ]:
df.loc[df['층']>7,:].head(3)

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
5   202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
7   202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  130000  2020  6  24   
12  202006  서울특별시종로구  11110  내수동              경희궁의아침3단지  172000  2020  6   5   

    건축년도    전용면적   층  
5   2008   91.35  14  
7   2008   94.51  14  
12  2004  174.55  11

In [ ]:
df['층']

0       5
1       7
2       5
3       1
4       5
       ..
113    13
114     2
115     9
116     6
117     4
Name: 층, Length: 118, dtype: int64

In [ ]:
df.loc[(df['아파트']=='인왕산아이파크') & (df['전용면적']>=100) ]

기준년월       지역명   지역코드  법정동      아파트    거래금액     년  월   일  건축년도  \
106  202006  서울특별시종로구  11110  무악동  인왕산아이파크  135000  2020  6  16  2008   
109  202006  서울특별시종로구  11110  무악동  인왕산아이파크  139000  2020  6  17  2008   

        전용면적   층  
106  114.931  12  
109  114.931  13

In [ ]:
df

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df.iloc[:10,5:]

거래금액     년  월   일  건축년도    전용면적   층
0  100000  2020  6  30  2002  134.66   5
1  121500  2020  6   4  2008  126.34   7
2  115000  2020  6   9  2008   94.28   5
3  113000  2020  6  13  2008   97.61   1
4  124000  2020  6  16  2008   94.51   5
5  120000  2020  6  20  2008   91.35  14
6  146000  2020  6  22  2008  150.40   7
7  130000  2020  6  24  2008   94.51  14
8  112000  2020  6  24  2008   94.28   1
9  145000  2020  6  26  2008  126.34   6

In [ ]:
df.iloc[-1]

기준년월      202006
지역명     서울특별시종로구
지역코드       11110
법정동          무악동
아파트           현대
거래금액      110900
년           2020
월              6
일             30
건축년도        2000
전용면적       114.9
층              4
Name: 117, dtype: object

In [ ]:
df['층'] ==7

0      False
1       True
2      False
3      False
4      False
       ...  
113    False
114    False
115    False
116    False
117    False
Name: 층, Length: 118, dtype: bool

In [ ]:
df.loc[~(df['층'] ==7)]

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
5    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
5    2008   91.350  14  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[107 rows x 12 columns]

In [ ]:
df.loc[df['층'] !=7]

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
5    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
5    2008   91.350  14  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[107 rows x 12 columns]

In [ ]:
df.loc[~(df['층']==7)]

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
5    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
5    2008   91.350  14  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[107 rows x 12 columns]

In [ ]:
df.iloc[:,0]

0      202006
1      202006
2      202006
3      202006
4      202006
        ...  
113    202006
114    202006
115    202006
116    202006
117    202006
Name: 기준년월, Length: 118, dtype: int64

In [ ]:
df.iloc[:10,5:]

거래금액     년  월   일  건축년도    전용면적   층
0  100000  2020  6  30  2002  134.66   5
1  121500  2020  6   4  2008  126.34   7
2  115000  2020  6   9  2008   94.28   5
3  113000  2020  6  13  2008   97.61   1
4  124000  2020  6  16  2008   94.51   5
5  120000  2020  6  20  2008   91.35  14
6  146000  2020  6  22  2008  150.40   7
7  130000  2020  6  24  2008   94.51  14
8  112000  2020  6  24  2008   94.28   1
9  145000  2020  6  26  2008  126.34   6

In [ ]:
df.iloc[0:5,5:10]

거래금액     년  월   일  건축년도
0  100000  2020  6  30  2002
1  121500  2020  6   4  2008
2  115000  2020  6   9  2008
3  113000  2020  6  13  2008
4  124000  2020  6  16  2008

In [ ]:
df.loc[df['층']!=7]

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
5    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
5    2008   91.350  14  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[107 rows x 12 columns]

In [ ]:
df.select_dtypes(include=object)

지역명  법정동                    아파트
0    서울특별시종로구  신교동               신현(102동)
1    서울특별시종로구  사직동  광화문풍림스페이스본(101동~105동)
2    서울특별시종로구  사직동  광화문풍림스페이스본(101동~105동)
3    서울특별시종로구  사직동  광화문풍림스페이스본(101동~105동)
4    서울특별시종로구  사직동  광화문풍림스페이스본(101동~105동)
..        ...  ...                    ...
113  서울특별시종로구  무악동                     현대
114  서울특별시종로구  무악동                인왕산아이파크
115  서울특별시종로구  무악동                인왕산아이파크
116  서울특별시종로구  무악동                     현대
117  서울특별시종로구  무악동                     현대

[118 rows x 3 columns]

In [ ]:
df.select_dtypes(exclude=object)

기준년월   지역코드    거래금액     년  월   일  건축년도     전용면적   층
0    202006  11110  100000  2020  6  30  2002  134.660   5
1    202006  11110  121500  2020  6   4  2008  126.340   7
2    202006  11110  115000  2020  6   9  2008   94.280   5
3    202006  11110  113000  2020  6  13  2008   97.610   1
4    202006  11110  124000  2020  6  16  2008   94.510   5
..      ...    ...     ...   ... ..  ..   ...      ...  ..
113  202006  11110  100990  2020  6  23  2000   84.920  13
114  202006  11110   97000  2020  6  23  2008   84.858   2
115  202006  11110  120000  2020  6  27  2008   84.858   9
116  202006  11110   74990  2020  6  27  2000   60.000   6
117  202006  11110  110900  2020  6  30  2000  114.900   4

[118 rows x 9 columns]

In [ ]:
df.reset_index()

index    기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  \
0        0  202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020   
1        1  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020   
2        2  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020   
3        3  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020   
4        4  202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020   
..     ...     ...       ...    ...  ...                    ...     ...   ...   
113    113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020   
114    114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020   
115    115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020   
116    116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020   
117    117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020   

     월   일  건축년도     전용면적   층  
0    6  30  2002  134.660   5  
1    6   4  2008  126.340   7  
2    6   9  2008   94.280   5  
3    6  13  2008   97.610   1  
4    6  16  2008   94.510   5  
..  ..  ..   ...      ...  ..  
113  6  23  2000   84.920  13  
114  6  23  2008   84.858   2  
115  6  27  2008   84.858   9  
116  6  27  2000   60.000   6  
117  6  30  2000  114.900   4  

[118 rows x 13 columns]

In [ ]:
df.reset_index(drop=True)

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df['지역명'].head()

0    서울특별시종로구
1    서울특별시종로구
2    서울특별시종로구
3    서울특별시종로구
4    서울특별시종로구
Name: 지역명, dtype: object

In [ ]:
df['지역명'].str[:2].head()

0    서울
1    서울
2    서울
3    서울
4    서울
Name: 지역명, dtype: object

In [ ]:
df['지역명'].str[:5].head()

0    서울특별시
1    서울특별시
2    서울특별시
3    서울특별시
4    서울특별시
Name: 지역명, dtype: object

In [ ]:
df['지역명']

0      서울특별시종로구
1      서울특별시종로구
2      서울특별시종로구
3      서울특별시종로구
4      서울특별시종로구
         ...   
113    서울특별시종로구
114    서울특별시종로구
115    서울특별시종로구
116    서울특별시종로구
117    서울특별시종로구
Name: 지역명, Length: 118, dtype: object

In [ ]:
df['지역명'].str.replace('서울특별시','서울시 ')

0      서울시 종로구
1      서울시 종로구
2      서울시 종로구
3      서울시 종로구
4      서울시 종로구
        ...   
113    서울시 종로구
114    서울시 종로구
115    서울시 종로구
116    서울시 종로구
117    서울시 종로구
Name: 지역명, Length: 118, dtype: object

In [ ]:
df

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df['지역명'] = df['지역명'].str.replace('서울특별시','서울시 ')

In [ ]:
df

기준년월      지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울시 종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울시 종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울시 종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울시 종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울시 종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...      ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울시 종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울시 종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울시 종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울시 종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울시 종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df['지역명'] = df['지역명'].str.replace('서울시 ','서울특별시')

In [ ]:
df

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0    202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
0    2002  134.660   5  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[118 rows x 12 columns]

In [ ]:
df[df['아파트'].str.contains('경희궁')].head(10)

기준년월       지역명   지역코드  법정동         아파트    거래금액     년  월   일  건축년도  \
11  202006  서울특별시종로구  11110  내수동   경희궁의아침2단지  140000  2020  6   1  2004   
12  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  172000  2020  6   5  2004   
14  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  155000  2020  6   9  2004   
15  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  178500  2020  6  16  2004   
17  202006  서울특별시종로구  11110  내수동   경희궁의아침2단지  170000  2020  6  22  2004   
78  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  141500  2020  6   3  2017   
79  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  170000  2020  6  17  2017   
80  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  169000  2020  6  18  2017   
81  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  137000  2020  6  20  2017   
82  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  140000  2020  6  29  2017   

       전용면적   층  
11  124.170   4  
12  174.550  11  
14  149.000  14  
15  174.550   7  
17  174.550  10  
78   59.855   7  
79   84.836   4  
80   84.836   9  
81   59.855   3  
82   59.855   5

In [ ]:
df.loc[df['아파트'].str.contains('경희궁')].head(10)

기준년월       지역명   지역코드  법정동         아파트    거래금액     년  월   일  건축년도  \
11  202006  서울특별시종로구  11110  내수동   경희궁의아침2단지  140000  2020  6   1  2004   
12  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  172000  2020  6   5  2004   
14  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  155000  2020  6   9  2004   
15  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  178500  2020  6  16  2004   
17  202006  서울특별시종로구  11110  내수동   경희궁의아침2단지  170000  2020  6  22  2004   
78  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  141500  2020  6   3  2017   
79  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  170000  2020  6  17  2017   
80  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  169000  2020  6  18  2017   
81  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  137000  2020  6  20  2017   
82  202006  서울특별시종로구  11110   평동  경희궁자이(3단지)  140000  2020  6  29  2017   

       전용면적   층  
11  124.170   4  
12  174.550  11  
14  149.000  14  
15  174.550   7  
17  174.550  10  
78   59.855   7  
79   84.836   4  
80   84.836   9  
81   59.855   3  
82   59.855   5

In [ ]:
df['아파트'].str.startswith('신현').head(12)

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
Name: 아파트, dtype: bool

In [ ]:
df.loc[df['아파트'].str.startswith('신현')]

기준년월       지역명   지역코드  법정동       아파트    거래금액     년  월   일  건축년도    전용면적  \
0  202006  서울특별시종로구  11110  신교동  신현(102동)  100000  2020  6  30  2002  134.66   

   층  
0  5

In [ ]:
df[~df['아파트'].str.startswith('신현')]

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
1    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
2    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   9   
3    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6  13   
4    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6  16   
5    202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  120000  2020  6  20   
..      ...       ...    ...  ...                    ...     ...   ... ..  ..   
113  202006  서울특별시종로구  11110  무악동                     현대  100990  2020  6  23   
114  202006  서울특별시종로구  11110  무악동                인왕산아이파크   97000  2020  6  23   
115  202006  서울특별시종로구  11110  무악동                인왕산아이파크  120000  2020  6  27   
116  202006  서울특별시종로구  11110  무악동                     현대   74990  2020  6  27   
117  202006  서울특별시종로구  11110  무악동                     현대  110900  2020  6  30   

     건축년도     전용면적   층  
1    2008  126.340   7  
2    2008   94.280   5  
3    2008   97.610   1  
4    2008   94.510   5  
5    2008   91.350  14  
..    ...      ...  ..  
113  2000   84.920  13  
114  2008   84.858   2  
115  2008   84.858   9  
116  2000   60.000   6  
117  2000  114.900   4  

[117 rows x 12 columns]

In [ ]:
df[df['아파트'].isin(['창신쌍용1'])].head(5)

기준년월       지역명   지역코드  법정동    아파트   거래금액     년  월   일  건축년도    전용면적   층
27  202006  서울특별시종로구  11110  창신동  창신쌍용1  75300  2020  6   1  1992  106.62  13
30  202006  서울특별시종로구  11110  창신동  창신쌍용1  67000  2020  6   3  1992   79.87  12
33  202006  서울특별시종로구  11110  창신동  창신쌍용1  64000  2020  6   7  1992   79.87   8
34  202006  서울특별시종로구  11110  창신동  창신쌍용1  52500  2020  6   8  1992   54.70   7
44  202006  서울특별시종로구  11110  창신동  창신쌍용1  61800  2020  6  15  1992   79.87   2

In [ ]:
df[df['아파트'].isin(['창신쌍용1','세종'])].head(5)

기준년월       지역명   지역코드  법정동    아파트   거래금액     년  월   일  건축년도    전용면적   층
10  202006  서울특별시종로구  11110  당주동     세종  79000  2020  6  15  1983  102.89   5
27  202006  서울특별시종로구  11110  창신동  창신쌍용1  75300  2020  6   1  1992  106.62  13
30  202006  서울특별시종로구  11110  창신동  창신쌍용1  67000  2020  6   3  1992   79.87  12
33  202006  서울특별시종로구  11110  창신동  창신쌍용1  64000  2020  6   7  1992   79.87   8
34  202006  서울특별시종로구  11110  창신동  창신쌍용1  52500  2020  6   8  1992   54.70   7

In [ ]:
df_price = df['거래금액']

In [ ]:
df_price

0      100000
1      121500
2      115000
3      113000
4      124000
        ...  
113    100990
114     97000
115    120000
116     74990
117    110900
Name: 거래금액, Length: 118, dtype: int64

In [ ]:
df_price.rolling(5).sum()

0           NaN
1           NaN
2           NaN
3           NaN
4      573500.0
         ...   
113    576880.0
114    534880.0
115    542890.0
116    502880.0
117    503880.0
Name: 거래금액, Length: 118, dtype: float64

In [ ]:
df_price.rolling(5).mean()

0           NaN
1           NaN
2           NaN
3           NaN
4      114700.0
         ...   
113    115376.0
114    106976.0
115    108578.0
116    100576.0
117    100776.0
Name: 거래금액, Length: 118, dtype: float64

In [ ]:
df.shift(1).head(5)

기준년월       지역명     지역코드   법정동                    아파트      거래금액       년  \
0       NaN      None      NaN  None                   None       NaN     NaN   
1  202006.0  서울특별시종로구  11110.0   신교동               신현(102동)  100000.0  2020.0   
2  202006.0  서울특별시종로구  11110.0   사직동  광화문풍림스페이스본(101동~105동)  121500.0  2020.0   
3  202006.0  서울특별시종로구  11110.0   사직동  광화문풍림스페이스본(101동~105동)  115000.0  2020.0   
4  202006.0  서울특별시종로구  11110.0   사직동  광화문풍림스페이스본(101동~105동)  113000.0  2020.0   

     월     일    건축년도    전용면적    층  
0  NaN   NaN     NaN     NaN  NaN  
1  6.0  30.0  2002.0  134.66  5.0  
2  6.0   4.0  2008.0  126.34  7.0  
3  6.0   9.0  2008.0   94.28  5.0  
4  6.0  13.0  2008.0   97.61  1.0

In [ ]:
df.shift(-1).head(5)

기준년월       지역명     지역코드  법정동                    아파트      거래금액       년  \
0  202006.0  서울특별시종로구  11110.0  사직동  광화문풍림스페이스본(101동~105동)  121500.0  2020.0   
1  202006.0  서울특별시종로구  11110.0  사직동  광화문풍림스페이스본(101동~105동)  115000.0  2020.0   
2  202006.0  서울특별시종로구  11110.0  사직동  광화문풍림스페이스본(101동~105동)  113000.0  2020.0   
3  202006.0  서울특별시종로구  11110.0  사직동  광화문풍림스페이스본(101동~105동)  124000.0  2020.0   
4  202006.0  서울특별시종로구  11110.0  사직동  광화문풍림스페이스본(101동~105동)  120000.0  2020.0   

     월     일    건축년도    전용면적     층  
0  6.0   4.0  2008.0  126.34   7.0  
1  6.0   9.0  2008.0   94.28   5.0  
2  6.0  13.0  2008.0   97.61   1.0  
3  6.0  16.0  2008.0   94.51   5.0  
4  6.0  20.0  2008.0   91.35  14.0

In [ ]:
df.sort_values('전용면적',ascending=True)

기준년월       지역명   지역코드  법정동        아파트    거래금액     년  월   일  건축년도  \
75  202006  서울특별시종로구  11110  숭인동  숭인한양LEEPS   11200  2020  6  18  2014   
74  202006  서울특별시종로구  11110  숭인동    삼전솔하임4차   13500  2020  6  17  2014   
76  202006  서울특별시종로구  11110  숭인동      버넷하임1   12900  2020  6  24  2013   
68  202006  서울특별시종로구  11110  숭인동   종로중흥S클래스   13600  2020  6  10  2013   
63  202006  서울특별시종로구  11110  창신동        동대문   40000  2020  6  29  1966   
..     ...       ...    ...  ...        ...     ...   ... ..  ..   ...   
15  202006  서울특별시종로구  11110  내수동  경희궁의아침3단지  178500  2020  6  16  2004   
12  202006  서울특별시종로구  11110  내수동  경희궁의아침3단지  172000  2020  6   5  2004   
99  202006  서울특별시종로구  11110  평창동       엘리시아   80000  2020  6  19  2009   
98  202006  서울특별시종로구  11110  평창동       엘리시아   85000  2020  6  17  2009   
16  202006  서울특별시종로구  11110  내수동       킹스매너  158000  2020  6  16  2004   

       전용면적   층  
75   12.780   8  
74   15.090  16  
76   17.960  12  
68   19.466   9  
63   28.800   2  
..      ...  ..  
15  174.550   7  
12  174.550  11  
99  200.190   5  
98  200.190   3  
16  218.860   2  

[118 rows x 12 columns]

In [ ]:
df.sort_values(['법정동', '전용면적'],ascending=True)

기준년월       지역명   지역코드  법정동         아파트    거래금액     년  월   일  건축년도  \
93  202006  서울특별시종로구  11110  교북동          동아   62000  2020  6  16  1995   
94  202006  서울특별시종로구  11110  구기동        마운틴뷰   40000  2020  6  12  2019   
13  202006  서울특별시종로구  11110  내수동       세종로대우   95000  2020  6   5  1994   
11  202006  서울특별시종로구  11110  내수동   경희궁의아침2단지  140000  2020  6   1  2004   
14  202006  서울특별시종로구  11110  내수동   경희궁의아침3단지  155000  2020  6   9  2004   
..     ...       ...    ...  ...         ...     ...   ... ..  ..   ...   
88  202006  서울특별시종로구  11110  홍파동  경희궁자이(2단지)  163500  2020  6  27  2017   
92  202006  서울특별시종로구  11110  홍파동  경희궁자이(2단지)  162500  2020  6  30  2017   
86  202006  서울특별시종로구  11110  홍파동  경희궁자이(2단지)  160500  2020  6  25  2017   
85  202006  서울특별시종로구  11110  홍파동  경희궁자이(2단지)  160000  2020  6  22  2017   
87  202006  서울특별시종로구  11110  홍파동  경희궁자이(2단지)  166000  2020  6  26  2017   

       전용면적   층  
93   59.980  10  
94   76.660   1  
13  109.910  11  
11  124.170   4  
14  149.000  14  
..      ...  ..  
88   84.907   6  
92   84.907  19  
86   84.944   4  
85   84.990   4  
87   84.990  18  

[118 rows x 12 columns]

In [ ]:
df.drop_duplicates(['법정동','아파트'],keep='first').head()

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0   202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1   202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
6   202006  서울특별시종로구  11110  사직동       광화문풍림스페이스본(106동)  146000  2020  6  22   
10  202006  서울특별시종로구  11110  당주동                     세종   79000  2020  6  15   
11  202006  서울특별시종로구  11110  내수동              경희궁의아침2단지  140000  2020  6   1   

    건축년도    전용면적  층  
0   2002  134.66  5  
1   2008  126.34  7  
6   2008  150.40  7  
10  1983  102.89  5  
11  2004  124.17  4

In [ ]:
df.groupby('법정동').min().head()

기준년월       지역명   지역코드        아파트   거래금액     년  월   일  건축년도    전용면적   층
법정동                                                                           
교북동   202006  서울특별시종로구  11110         동아  62000  2020  6  16  1995   59.98  10
구기동   202006  서울특별시종로구  11110       마운틴뷰  40000  2020  6  12  2019   76.66   1
내수동   202006  서울특별시종로구  11110  경희궁의아침2단지  95000  2020  6   1  1994  109.91   2
당주동   202006  서울특별시종로구  11110         세종  79000  2020  6  15  1983  102.89   5
명륜2가  202006  서울특별시종로구  11110        아남1  89500  2020  6   4  1995   84.90   4

In [ ]:
df.groupby('법정동',as_index=False).max().head()

법정동    기준년월       지역명   지역코드   아파트    거래금액     년  월   일  건축년도    전용면적   층
0   교북동  202006  서울특별시종로구  11110    동아   62000  2020  6  16  1995   59.98  10
1   구기동  202006  서울특별시종로구  11110  마운틴뷰   40000  2020  6  12  2019   76.66   1
2   내수동  202006  서울특별시종로구  11110  킹스매너  178500  2020  6  22  2004  218.86  14
3   당주동  202006  서울특별시종로구  11110    세종   79000  2020  6  15  1983  102.89   5
4  명륜2가  202006  서울특별시종로구  11110   아남1   89900  2020  6  13  1995   84.90   8

In [ ]:
df.groupby('법정동').agg(['size', 'max']).head()

기준년월          지역명           지역코드         아파트       거래금액          ...  \
     size     max size       max size    max size   max size     max  ...   
법정동                                                                   ...   
교북동     1  202006    1  서울특별시종로구    1  11110    1    동아    1   62000  ...   
구기동     1  202006    1  서울특별시종로구    1  11110    1  마운틴뷰    1   40000  ...   
내수동     7  202006    7  서울특별시종로구    7  11110    7  킹스매너    7  178500  ...   
당주동     1  202006    1  서울특별시종로구    1  11110    1    세종    1   79000  ...   
명륜2가    2  202006    2  서울특별시종로구    2  11110    2   아남1    2   89900  ...   

        월        일     건축년도       전용면적            층      
     size max size max size   max size     max size max  
법정동                                                      
교북동     1   6    1  16    1  1995    1   59.98    1  10  
구기동     1   6    1  12    1  2019    1   76.66    1   1  
내수동     7   6    7  22    7  2004    7  218.86    7  14  
당주동     1   6    1  15    1  1983    1  102.89    1   5  
명륜2가    2   6    2  13    2  1995    2   84.90    2   8  

[5 rows x 22 columns]

In [ ]:
df.groupby(['법정동','아파트']).max().unstack()

기준년월                                            \
아파트  MID그린(8동) 경희궁의아침2단지 경희궁의아침3단지 경희궁자이(2단지) 경희궁자이(3단지)   
법정동                                                        
교북동        NaN       NaN       NaN        NaN        NaN   
구기동        NaN       NaN       NaN        NaN        NaN   
내수동        NaN  202006.0  202006.0        NaN        NaN   
당주동        NaN       NaN       NaN        NaN        NaN   
명륜2가       NaN       NaN       NaN        NaN        NaN   
무악동        NaN       NaN       NaN        NaN        NaN   
사직동        NaN       NaN       NaN        NaN        NaN   
숭인동        NaN       NaN       NaN        NaN        NaN   
신교동        NaN       NaN       NaN        NaN        NaN   
익선동        NaN       NaN       NaN        NaN        NaN   
인의동        NaN       NaN       NaN        NaN        NaN   
창신동   202006.0       NaN       NaN        NaN        NaN   
평동         NaN       NaN       NaN        NaN   202006.0   
평창동        NaN       NaN       NaN        NaN        NaN   
홍파동        NaN       NaN       NaN   202006.0        NaN   

                                                                           \
아파트  광화문풍림스페이스본(101동~105동) 광화문풍림스페이스본(106동)       동대문     동대문맨션        동아   
법정동                                                                         
교북동                    NaN              NaN       NaN       NaN  202006.0   
구기동                    NaN              NaN       NaN       NaN       NaN   
내수동                    NaN              NaN       NaN       NaN       NaN   
당주동                    NaN              NaN       NaN       NaN       NaN   
명륜2가                   NaN              NaN       NaN       NaN       NaN   
무악동                    NaN              NaN       NaN       NaN       NaN   
사직동               202006.0         202006.0       NaN       NaN       NaN   
숭인동                    NaN              NaN       NaN       NaN       NaN   
신교동                    NaN              NaN       NaN       NaN       NaN   
익선동                    NaN              NaN       NaN       NaN       NaN   
인의동                    NaN              NaN       NaN       NaN       NaN   
창신동                    NaN              NaN  202006.0  202006.0       NaN   
평동                     NaN              NaN       NaN       NaN       NaN   
평창동                    NaN              NaN       NaN       NaN       NaN   
홍파동                    NaN              NaN       NaN       NaN       NaN   

      ...    층                                                                  
아파트   ...   일우 종로센트레빌 종로중흥S클래스 종로청계힐스테이트 창신쌍용1 창신쌍용2 킹스매너    현대 현대뜨레비앙 효성쥬얼리시티  
법정동   ...                                                                       
교북동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
구기동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
내수동   ...  NaN    NaN      NaN       NaN   NaN   NaN  2.0   NaN    NaN     NaN  
당주동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
명륜2가  ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
무악동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN  18.0    NaN     NaN  
사직동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
숭인동   ...  NaN   10.0      9.0      18.0   NaN   NaN  NaN   NaN    NaN     NaN  
신교동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
익선동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    9.0     NaN  
인의동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN    19.0  
창신동   ...  6.0    NaN      NaN       NaN  13.0  10.0  NaN   NaN    NaN     NaN  
평동    ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
평창동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  
홍파동   ...  NaN    NaN      NaN       NaN   NaN   NaN  NaN   NaN    NaN     NaN  

[15 rows x 380 columns]

In [ ]:
df_pivot = df.drop_duplicates(['법정동','아파트'],keep='first')[:10]

In [ ]:
df_pivot

기준년월       지역명   지역코드  법정동                    아파트    거래금액     년  월   일  \
0   202006  서울특별시종로구  11110  신교동               신현(102동)  100000  2020  6  30   
1   202006  서울특별시종로구  11110  사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   4   
6   202006  서울특별시종로구  11110  사직동       광화문풍림스페이스본(106동)  146000  2020  6  22   
10  202006  서울특별시종로구  11110  당주동                     세종   79000  2020  6  15   
11  202006  서울특별시종로구  11110  내수동              경희궁의아침2단지  140000  2020  6   1   
12  202006  서울특별시종로구  11110  내수동              경희궁의아침3단지  172000  2020  6   5   
13  202006  서울특별시종로구  11110  내수동                  세종로대우   95000  2020  6   5   
16  202006  서울특별시종로구  11110  내수동                   킹스매너  158000  2020  6  16   
18  202006  서울특별시종로구  11110  익선동                 현대뜨레비앙   36000  2020  6   2   
19  202006  서울특별시종로구  11110  익선동                 운현신화타워   47000  2020  6  18   

    건축년도    전용면적   층  
0   2002  134.66   5  
1   2008  126.34   7  
6   2008  150.40   7  
10  1983  102.89   5  
11  2004  124.17   4  
12  2004  174.55  11  
13  1994  109.91  11  
16  2004  218.86   2  
18  2003   48.54   9  
19  1998   50.31  14

In [ ]:
df_pivot1 = df_pivot.pivot(index='법정동', columns='아파트', values='거래금액')
df_pivot1

아파트  경희궁의아침2단지  경희궁의아침3단지  광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(106동)       세종  \
법정동                                                                           
내수동   140000.0   172000.0                    NaN               NaN      NaN   
당주동        NaN        NaN                    NaN               NaN  79000.0   
사직동        NaN        NaN               121500.0          146000.0      NaN   
신교동        NaN        NaN                    NaN               NaN      NaN   
익선동        NaN        NaN                    NaN               NaN      NaN   

아파트    세종로대우  신현(102동)   운현신화타워      킹스매너   현대뜨레비앙  
법정동                                                 
내수동  95000.0       NaN      NaN  158000.0      NaN  
당주동      NaN       NaN      NaN       NaN      NaN  
사직동      NaN       NaN      NaN       NaN      NaN  
신교동      NaN  100000.0      NaN       NaN      NaN  
익선동      NaN       NaN  47000.0       NaN  36000.0

In [ ]:
df_pivot.pivot(index='법정동', columns='아파트', values='거래금액').fillna(0)

아파트  경희궁의아침2단지  경희궁의아침3단지  광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(106동)       세종  \
법정동                                                                           
내수동   140000.0   172000.0                    0.0               0.0      0.0   
당주동        0.0        0.0                    0.0               0.0  79000.0   
사직동        0.0        0.0               121500.0          146000.0      0.0   
신교동        0.0        0.0                    0.0               0.0      0.0   
익선동        0.0        0.0                    0.0               0.0      0.0   

아파트    세종로대우  신현(102동)   운현신화타워      킹스매너   현대뜨레비앙  
법정동                                                 
내수동  95000.0       0.0      0.0  158000.0      0.0  
당주동      0.0       0.0      0.0       0.0      0.0  
사직동      0.0       0.0      0.0       0.0      0.0  
신교동      0.0  100000.0      0.0       0.0      0.0  
익선동      0.0       0.0  47000.0       0.0  36000.0

In [ ]:
df_pivot.pivot_table(index='법정동',columns='아파트',values='전용면적',aggfunc='max').fillna(0)

아파트  경희궁의아침2단지  경희궁의아침3단지  광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(106동)      세종  \
법정동                                                                          
내수동     124.17     174.55                   0.00               0.0    0.00   
당주동       0.00       0.00                   0.00               0.0  102.89   
사직동       0.00       0.00                 126.34             150.4    0.00   
신교동       0.00       0.00                   0.00               0.0    0.00   
익선동       0.00       0.00                   0.00               0.0    0.00   

아파트   세종로대우  신현(102동)  운현신화타워    킹스매너  현대뜨레비앙  
법정동                                            
내수동  109.91      0.00    0.00  218.86    0.00  
당주동    0.00      0.00    0.00    0.00    0.00  
사직동    0.00      0.00    0.00    0.00    0.00  
신교동    0.00    134.66    0.00    0.00    0.00  
익선동    0.00      0.00   50.31    0.00   48.54

In [ ]:
df.T

0                      1                      2    \
기준년월    202006                 202006                 202006   
지역명   서울특별시종로구               서울특별시종로구               서울특별시종로구   
지역코드     11110                  11110                  11110   
법정동        신교동                    사직동                    사직동   
아파트   신현(102동)  광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(101동~105동)   
거래금액    100000                 121500                 115000   
년         2020                   2020                   2020   
월            6                      6                      6   
일           30                      4                      9   
건축년도      2002                   2008                   2008   
전용면적    134.66                 126.34                  94.28   
층            5                      7                      5   

                        3                      4                      5    \
기준년월                 202006                 202006                 202006   
지역명                서울특별시종로구               서울특별시종로구               서울특별시종로구   
지역코드                  11110                  11110                  11110   
법정동                     사직동                    사직동                    사직동   
아파트   광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(101동~105동)   
거래금액                 113000                 124000                 120000   
년                      2020                   2020                   2020   
월                         6                      6                      6   
일                        13                     16                     20   
건축년도                   2008                   2008                   2008   
전용면적                  97.61                  94.51                  91.35   
층                         1                      5                     14   

                   6                      7                      8    \
기준년월            202006                 202006                 202006   
지역명           서울특별시종로구               서울특별시종로구               서울특별시종로구   
지역코드             11110                  11110                  11110   
법정동                사직동                    사직동                    사직동   
아파트   광화문풍림스페이스본(106동)  광화문풍림스페이스본(101동~105동)  광화문풍림스페이스본(101동~105동)   
거래금액            146000                 130000                 112000   
년                 2020                   2020                   2020   
월                    6                      6                      6   
일                   22                     24                     24   
건축년도              2008                   2008                   2008   
전용면적             150.4                  94.51                  94.28   
층                    7                     14                      1   

                        9    ...       108       109       110       111  \
기준년월                 202006  ...    202006    202006    202006    202006   
지역명                서울특별시종로구  ...  서울특별시종로구  서울특별시종로구  서울특별시종로구  서울특별시종로구   
지역코드                  11110  ...     11110     11110     11110     11110   
법정동                     사직동  ...       무악동       무악동       무악동       무악동   
아파트   광화문풍림스페이스본(101동~105동)  ...        현대   인왕산아이파크        현대        현대   
거래금액                 145000  ...    101460    139000    111990    115000   
년                      2020  ...      2020      2020      2020      2020   
월                         6  ...         6         6         6         6   
일                        26  ...        16        17        18        20   
건축년도                   2008  ...      2000      2008      2000      2000   
전용면적                 126.34  ...     84.92   114.931     114.9     114.9   
층                         6  ...        14        13        12         7   

           112       113       114       115       116       117  
기준년월    202006    202006    202006    202006    202006    202006  
지역명   서울특별시종로구  서울특별시종로구  서울특별시종로구  서울특별시종로구  서울특별시종로구  서울특별시종로구  
지역코드     11110     11110     11110     11110     

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/kdt_2506/data/trade_apt_api_date.csv')

In [ ]:
df

기준년월       지역명   지역코드   법정동                    아파트    거래금액     년  월  \
0    202006  서울특별시종로구  11110   신교동               신현(102동)  100000  2020  6   
1    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   
2    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   
3    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6   
4    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6   
..      ...       ...    ...   ...                    ...     ...   ... ..   
113  202006  서울특별시종로구  11110   무악동                     현대  100990  2020  6   
114  202006  서울특별시종로구  11110   무악동                인왕산아이파크   97000  2020  6   
115  202006  서울특별시종로구  11110   무악동                인왕산아이파크  120000  2020  6   
116  202006  서울특별시종로구  11110   무악동                     현대   74990  2020  6   
117  202006  서울특별시종로구  11110   무악동                     현대  110900  2020  6   

      일  건축년도     전용면적   층       date  
0    30  2002  134.660   5  2020.6.30  
1     4  2008  126.340   7   2020.6.4  
2     9  2008   94.280   5   2020.6.9  
3    13  2008   97.610   1  2020.6.13  
4    16  2008   94.510   5  2020.6.16  
..   ..   ...      ...  ..        ...  
113  23  2000   84.920  13  2020.6.23  
114  23  2008   84.858   2  2020.6.23  
115  27  2008   84.858   9  2020.6.27  
116  27  2000   60.000   6  2020.6.27  
117  30  2000  114.900   4  2020.6.30  

[118 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   기준년월    118 non-null    int64  
 1   지역명     118 non-null    object 
 2   지역코드    118 non-null    int64  
 3   법정동     118 non-null    object 
 4   아파트     118 non-null    object 
 5   거래금액    118 non-null    int64  
 6   년       118 non-null    int64  
 7   월       118 non-null    int64  
 8   일       118 non-null    int64  
 9   건축년도    118 non-null    int64  
 10  전용면적    118 non-null    float64
 11  층       118 non-null    int64  
 12  date    118 non-null    object 
dtypes: float64(1), int64(8), object(4)
memory usage: 12.1+ KB


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/kdt_2506/data/trade_apt_api_date.csv',parse_dates=["date"])

In [ ]:
df

기준년월       지역명   지역코드   법정동                    아파트    거래금액     년  월  \
0    202006  서울특별시종로구  11110   신교동               신현(102동)  100000  2020  6   
1    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   
2    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   
3    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6   
4    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6   
..      ...       ...    ...   ...                    ...     ...   ... ..   
113  202006  서울특별시종로구  11110   무악동                     현대  100990  2020  6   
114  202006  서울특별시종로구  11110   무악동                인왕산아이파크   97000  2020  6   
115  202006  서울특별시종로구  11110   무악동                인왕산아이파크  120000  2020  6   
116  202006  서울특별시종로구  11110   무악동                     현대   74990  2020  6   
117  202006  서울특별시종로구  11110   무악동                     현대  110900  2020  6   

      일  건축년도     전용면적   층       date  
0    30  2002  134.660   5 2020-06-30  
1     4  2008  126.340   7 2020-06-04  
2     9  2008   94.280   5 2020-06-09  
3    13  2008   97.610   1 2020-06-13  
4    16  2008   94.510   5 2020-06-16  
..   ..   ...      ...  ..        ...  
113  23  2000   84.920  13 2020-06-23  
114  23  2008   84.858   2 2020-06-23  
115  27  2008   84.858   9 2020-06-27  
116  27  2000   60.000   6 2020-06-27  
117  30  2000  114.900   4 2020-06-30  

[118 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   기준년월    118 non-null    int64         
 1   지역명     118 non-null    object        
 2   지역코드    118 non-null    int64         
 3   법정동     118 non-null    object        
 4   아파트     118 non-null    object        
 5   거래금액    118 non-null    int64         
 6   년       118 non-null    int64         
 7   월       118 non-null    int64         
 8   일       118 non-null    int64         
 9   건축년도    118 non-null    int64         
 10  전용면적    118 non-null    float64       
 11  층       118 non-null    int64         
 12  date    118 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(8), object(3)
memory usage: 12.1+ KB


In [ ]:
df['date']

0     2020-06-30
1     2020-06-04
2     2020-06-09
3     2020-06-13
4     2020-06-16
         ...    
113   2020-06-23
114   2020-06-23
115   2020-06-27
116   2020-06-27
117   2020-06-30
Name: date, Length: 118, dtype: datetime64[ns]

In [ ]:
df['date'].dt.year

0      2020
1      2020
2      2020
3      2020
4      2020
       ... 
113    2020
114    2020
115    2020
116    2020
117    2020
Name: date, Length: 118, dtype: int32

In [ ]:
df['date'].dt.month

0      6
1      6
2      6
3      6
4      6
      ..
113    6
114    6
115    6
116    6
117    6
Name: date, Length: 118, dtype: int32

In [ ]:
df['date'].dt.day

0      30
1       4
2       9
3      13
4      16
       ..
113    23
114    23
115    27
116    27
117    30
Name: date, Length: 118, dtype: int32

In [ ]:
df['date'].dt.weekday

0      1
1      3
2      1
3      5
4      1
      ..
113    1
114    1
115    5
116    5
117    1
Name: date, Length: 118, dtype: int32

In [ ]:
df['Y_M'] = df['date'].dt.to_period(freq = 'M')

In [ ]:
df

기준년월       지역명   지역코드   법정동                    아파트    거래금액     년  월  \
0    202006  서울특별시종로구  11110   신교동               신현(102동)  100000  2020  6   
1    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  121500  2020  6   
2    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  115000  2020  6   
3    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  113000  2020  6   
4    202006  서울특별시종로구  11110   사직동  광화문풍림스페이스본(101동~105동)  124000  2020  6   
..      ...       ...    ...   ...                    ...     ...   ... ..   
113  202006  서울특별시종로구  11110   무악동                     현대  100990  2020  6   
114  202006  서울특별시종로구  11110   무악동                인왕산아이파크   97000  2020  6   
115  202006  서울특별시종로구  11110   무악동                인왕산아이파크  120000  2020  6   
116  202006  서울특별시종로구  11110   무악동                     현대   74990  2020  6   
117  202006  서울특별시종로구  11110   무악동                     현대  110900  2020  6   

      일  건축년도     전용면적   층       date      Y_M  
0    30  2002  134.660   5 2020-06-30  2020-06  
1     4  2008  126.340   7 2020-06-04  2020-06  
2     9  2008   94.280   5 2020-06-09  2020-06  
3    13  2008   97.610   1 2020-06-13  2020-06  
4    16  2008   94.510   5 2020-06-16  2020-06  
..   ..   ...      ...  ..        ...      ...  
113  23  2000   84.920  13 2020-06-23  2020-06  
114  23  2008   84.858   2 2020-06-23  2020-06  
115  27  2008   84.858   9 2020-06-27  2020-06  
116  27  2000   60.000   6 2020-06-27  2020-06  
117  30  2000  114.900   4 2020-06-30  2020-06  

[118 rows x 14 columns]